artist_links = {
   "Taylor Swift": "https://www.youtube.com/@TaylorSwift",
   "Ariana Grande": "https://www.youtube.com/@ArianaGrande",
   "Dua Lipa": "https://www.youtube.com/@dualipa",
   "Olivia Rodrigo": "https://www.youtube.com/@OliviaRodrigo",
   "Harry Styles": "https://www.youtube.com/@HarryStyles",
   "Drake": "https://www.youtube.com/@DrakeOfficial",
   "Travis Scott": "https://www.youtube.com/@TravisScottXX",
   "Lil Uzi Vert": "https://www.youtube.com/@liluzivert",
   "Kendrick Lamar": "https://www.youtube.com/@KendrickLamarVEVO",
   "J. Cole": "https://www.youtube.com/@jcole",
   "Imagine Dragons": "https://www.youtube.com/@ImagineDragons",
   "Foo Fighters": "https://www.youtube.com/@foofighters",
   "Arctic Monkeys": "https://www.youtube.com/@ArcticMonkeys",
   "Nirvana": "https://www.youtube.com/@Nirvana",
   "Green Day": "https://www.youtube.com/@GreenDay",
   "SZA": "https://www.youtube.com/@sza",
   "The Weeknd": "https://www.youtube.com/@TheWeeknd",
   "Brent Faiyaz": "https://www.youtube.com/channel/UCtdVC7nSYNOpKroA5JicNig",
   "H.E.R.": "https://www.youtube.com/@HERmusic",
   "Daniel Caesar": "https://www.youtube.com/@danielcaesar",
   "Nicki Minaj": "https://www.youtube.com/@nickiminaj",
   "21 Savage": "https://www.youtube.com/@21savage",
   "Lil Baby": "https://www.youtube.com/channel/UCVS88tG_NYgxF6Udnx2815Q"
}
